# Generated by Django 5.2.17 on 2026-08-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_per_hour', models.PositiveIntegerField(default=0, help_text="so'mda, 0 = bepul")),
                ('wifi_speed', models.PositiveIntegerField(default=0, help_text='Mbps')),
                ('socket_count', models.PositiveIntegerField(default=0, help_text='rozetkalar soni')),
                ('noise_level', models.CharField(choices=[('VERY_QUIET', 'Juda tinch'), ('QUIET', 'Tinch'), ('AVERAGE', "O'rtacha"), ('NOISY', 'Shovqinli')], default='AVERAGE', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=10, help_text="maksimal sig'im")),
                ('available_slots', models.PositiveIntegerField(default=0, help_text="hozirgi bo'sh joylar")),
                ('open_time', models.TimeField(default='08:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='PENDING', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.district')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_free', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_log', to='places.place')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['status', 'district'], name='places_plac_status_5b34bb_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['status', 'noise_level'], name='places_plac_status_19f7e5_idx'),
        ),
    ]
