# Generated by Django 5.2.17 on 2026-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
